"""initial_schema

Revision ID: e2f5f75139dd
Revises: 
Create Date: 2026-04-23 01:22:48.012710

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2f5f75139dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_profiles",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("competitors", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("queries_discovered", sa.Integer(), nullable=False),
        sa.Column("queries_scored", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"],
            ["business_profiles.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "discovered_queries",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("run_uuid", sa.Uuid(), nullable=False),
        sa.Column("query_text", sa.String(), nullable=False),
        sa.Column("estimated_search_volume", sa.Integer(), nullable=False),
        sa.Column("competitive_difficulty", sa.Integer(), nullable=False),
        sa.Column("opportunity_score", sa.Float(), nullable=False),
        sa.Column("domain_visible", sa.Boolean(), nullable=False),
        sa.Column("visibility_position", sa.Integer(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_uuid"],
            ["business_profiles.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["run_uuid"],
            ["pipeline_runs.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_discovered_queries_opportunity_score"),
        "discovered_queries",
        ["opportunity_score"],
        unique=False,
    )
    op.create_table(
        "content_recommendations",
        sa.Column("profile_uuid", sa.Uuid(), nullable=False),
        sa.Column("query_uuid", sa.Uuid(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("target_keywords", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["profile_uuid"],
            ["business_profiles.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["query_uuid"],
            ["discovered_queries.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_recommendations")
    op.drop_index(
        op.f("ix_discovered_queries_opportunity_score"), table_name="discovered_queries"
    )
    op.drop_table("discovered_queries")
    op.drop_table("pipeline_runs")
    op.drop_table("business_profiles")
    # ### end Alembic commands ###
